name: Automated Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: |
          go mod download

      - name: Set up Dart
        uses: subosito/setup-dart@v1
        with:
          dart-sdk: stable

      - name: Run Go tests with coverage
        run: |
          go test -v -coverprofile=coverage.txt ./...


      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.txt
